%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/santiago/Dropbox (Biophotonics)/Projects/FlatMounts/code/eMailQuRVA/imagesToProcess/Reports/AnalysisResult.xls
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/08/03 17:18:59
function AnalysisResult = openExcelReport(baseDir)
%% Import the data
% [~, ~, raw] = xlsread(fullfile(baseDir,'Reports','AnalysisResult.xlsx'),'Sheet1');
[~, ~, raw] = xlsread(fullfile(baseDir,'Reports','AnalysisResult.xlsx'));
raw = raw(2:end,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,1);
raw = raw(:,[2,3,4,5,6,7,8]);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
AnalysisResult = table;

%% Allocate imported array to column variable names
AnalysisResult.FileName = cellVectors(:,1);
AnalysisResult.FlatMountArea = data(:,1);
AnalysisResult.BranchingPoints = data(:,2);
AnalysisResult.AVascularArea = data(:,3);
AnalysisResult.VasculatureLength = data(:,4);
AnalysisResult.TuftArea = data(:,5);
AnalysisResult.TuftNumber = data(:,6);
AnalysisResult.EndPoints = data(:,7);


end
%% Clear temporary variables
% clearvars data raw cellVectors;